### ISSUE TITLE
[PARCIAL-ARCE] 

### ISSUE THREAD

**Issue by milagrosarce** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-milagrosarce#1]
@juanFdS

**Comment by JuanFdS** [comment]
Parte A
---

- Falta limitar entre 1 y 10 el poder innato
- tieneEstaCantLetrasPar no es un muy buen nombre porque no se sabe qué es lo que tiene que tener cantidad de letras par. Además podría haber reusado cantLetrasDelNombre. Una cosa más es que los números entienden .even() y .odd().
- El tipo de túnica común debería retornar 0 para que funcione.
- La ojota debería ser un objeto ya que hay una sola.
-  puedoGanarle está de más, podría usarse directo puedePerder
- Hay cierta repetición de lógica entre las categorías de aprendiz y veterano.
- No usemos variables con nombre aux

Parte B
---

- Bien lo de fundador, en general en la industria las clases que construyen nuevos objetos se llaman Builder, por ejemplo acá sería GremioBuilder o algo similar (solo para que estés al tanto)
- Una cosa con esto es que el líder debería ser un campo que se calcula cada vez, porque sino cada vez que sucede una acción tengo que guardarlo de nuevo.
- Incluso si lo guardara, no esta bueno inicializarlo en null, habría que tomar el que tenga mayor poder de los miembros iniciales.
- masPoderoso suena a nombre de que pregunto quién es el más poderoso, pero lo que hace es asignar algo en líder.
- En puedoGanarle, lo que se suam del líder debería ser del gremo enemigo. Acá se modeló como una lista de enemigos pero la idea es poder enfrentar a un gremio, quien tiene un líder.
- Bien el punto 3

Nota: 8
